@startuml

title __HA's Class Diagram__\n

  namespace com.mysql.cj {
    namespace jdbc {
      namespace ha {
        interface com.mysql.cj.jdbc.ha.BalanceStrategy {
            {abstract} + pickConnection()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace jdbc {
      namespace ha {
        interface com.mysql.cj.jdbc.ha.LoadBalanceExceptionChecker {
            {abstract} + destroy()
            {abstract} + init()
            {abstract} + shouldExceptionTriggerFailover()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace jdbc {
      namespace ha {
        interface com.mysql.cj.jdbc.ha.LoadBalancedConnection {
            {abstract} + addHost()
            {abstract} + ping()
            {abstract} + removeHost()
            {abstract} + removeHostWhenNotInUse()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace jdbc {
      namespace ha {
        interface com.mysql.cj.jdbc.ha.ReplicationConnection {
            {abstract} + addSlaveHost()
            {abstract} + getConnectionGroupId()
            {abstract} + getCurrentConnection()
            {abstract} + getMasterConnection()
            {abstract} + getSlavesConnection()
            {abstract} + isHostMaster()
            {abstract} + isHostSlave()
            {abstract} + promoteSlaveToMaster()
            {abstract} + removeMasterHost()
            {abstract} + removeMasterHost()
            {abstract} + removeSlave()
            {abstract} + removeSlave()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
