@startuml

title __X's Class Diagram__\n

  namespace com.mysql.cj {
    namespace protocol {
      namespace x {
        class com.mysql.cj.protocol.x.AsyncMessageReaderTest {
            + errorAfterClosed()
            + testBug22972057()
            + testBug22972057_getNextMessageClass()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace x {
        class com.mysql.cj.protocol.x.AsyncMessageReaderTest.BaseTestChannel {
            + open : boolean
            ~ readBuf : ByteBuffer
            ~ readHandler : CompletionHandler<Integer, ?>
            ~ writeHandler : CompletionHandler<Integer, ?>
            + bind()
            + close()
            + completeRead()
            + connect()
            + connect()
            + failRead()
            + getLocalAddress()
            + getOption()
            + getRemoteAddress()
            + isOpen()
            + read()
            + read()
            + read()
            + setOption()
            + shutdownInput()
            + shutdownOutput()
            + supportedOptions()
            + write()
            + write()
            + write()
            # BaseTestChannel()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace x {
        class com.mysql.cj.protocol.x.AsyncMessageReaderTest.BaseTestSocketConnection {
            ~ channel : AsynchronousSocketChannel
            + BaseTestSocketConnection()
            + connect()
            + forceClose()
            + getAsynchronousSocketChannel()
            + getExceptionInterceptor()
            + getHost()
            + getMysqlInput()
            + getMysqlOutput()
            + getMysqlSocket()
            + getNetworkResources()
            + getPort()
            + getPropertySet()
            + getSocketFactory()
            + isSSLEstablished()
            + performTlsHandshake()
            + setMysqlInput()
            + setSocketFactory()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace x {
        class com.mysql.cj.protocol.x.SyncMessageReaderTest {
            {static} - errMsgPacket : byte[]
            {static} - okMsgPacket : byte[]
            - reader : SyncMessageReader
            + setUp()
            + testMappingTables()
            + testNextMessageClass()
            + testReadKnownMessageType()
            + testReadWrongMessageType()
            + testSeveralMessages()
            + testUnexpectedError()
            {static} - serializeMessage()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace x {
        class com.mysql.cj.protocol.x.SyncMessageWriterTest {
            - outputStream : ByteArrayOutputStream
            - writer : SyncMessageSender
            + setUp()
            + testBadMessageClass()
            + testCompleteWriteMessage()
            + testLastPacketSentTime()
        }
      }
    }
  }
  

  com.mysql.cj.protocol.x.AsyncMessageReaderTest +-down- com.mysql.cj.protocol.x.AsyncMessageReaderTest.BaseTestChannel
  com.mysql.cj.protocol.x.AsyncMessageReaderTest +-down- com.mysql.cj.protocol.x.AsyncMessageReaderTest.BaseTestSocketConnection
  com.mysql.cj.protocol.x.AsyncMessageReaderTest.BaseTestSocketConnection .up.|> SocketConnection


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
