@startuml

title __XDEVAPI's Class Diagram__\n

  namespace com.mysql.cj {
    namespace xdevapi {
      class com.mysql.cj.xdevapi.ExprParserTest {
          + testBug95503()
          + testComplexTableSelectProjection()
          + testExprAsPathDocumentProjection()
          + testExprTree()
          + testJsonConstructorAsDocumentProjection()
          + testJsonExprsInDocumentProjection()
          + testJsonLiteral()
          + testNamedPlaceholders()
          + testNumberedPlaceholders()
          + testOrderByParserBasic()
          + testOrderByParserComplexExpressions()
          + testOverlaps()
          + testOverlapsInProjection()
          + testRandom()
          + testRoundTrips()
          + testStarTableSelectProjection()
          + testTableInsertProjection()
          + testTableUpdateField()
          + testTrivialDocumentProjection()
          + testTrivialTableSelectProjection()
          + testUnnumberedPlaceholders()
          + testUnparseables()
          + unqualifiedDocPaths()
          - checkBadParse()
          - checkParseRoundTrip()
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace xdevapi {
      class com.mysql.cj.xdevapi.JsonDocTest {
          + bracketAsValue()
          + testEscaping()
          + testJsonNumberAtEnd()
          + testParseArray()
          + testParseDoc()
          + testParseFalseLiteral()
          + testParseNullLiteral()
          + testParseNumber()
          + testParseString()
          + testParseTrueLiteral()
          + testToJsonString()
          {static} # assertThrows()
          {static} # assertThrows()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
