@startuml

title __URL's Class Diagram__\n

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.FailoverConnectionUrl {
            + FailoverConnectionUrl()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.LoadbalanceConnectionUrl {
            + LoadbalanceConnectionUrl()
            + LoadbalanceConnectionUrl()
            + getHostInfoListAsHostPortPairs()
            + getHostInfoListFromHostPortPairs()
            # injectPerTypeProperties()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.ReplicationConnectionUrl {
            {static} - TYPE_MASTER : String
            {static} - TYPE_SLAVE : String
            - masterHosts : List<HostInfo>
            - slaveHosts : List<HostInfo>
            + ReplicationConnectionUrl()
            + ReplicationConnectionUrl()
            + getMasterHostOrSpawnIsolated()
            + getMasterHostsListFromHostPortPairs()
            + getMastersList()
            + getMastersListAsHostPortPairs()
            + getSlaveHostOrSpawnIsolated()
            + getSlaveHostsListFromHostPortPairs()
            + getSlavesList()
            + getSlavesListAsHostPortPairs()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.SingleConnectionUrl {
            + SingleConnectionUrl()
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace conf {
      namespace url {
        class com.mysql.cj.conf.url.XDevAPIConnectionUrl {
            {static} - DEFAULT_PORT : int
            + XDevAPIConnectionUrl()
            + getDefaultPort()
            # fixProtocolDependencies()
            # preprocessPerTypeHostProperties()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
