@startuml

title __CJ's Class Diagram__\n

  namespace com.mysql.cj {
    class com.mysql.cj.ConnectionUrlTest {
        + testBug28150662()
        + testConnectionStringAcceptsUrl()
        + testConnectionStringCache()
        + testConnectionStringParser()
        + testConnectionUrl()
        + testConnectionUrlWithWrongConnectionString()
        + testDefaultValues()
        + testLoadingPropertiesFromConfigFiles()
        + testMysqlxConnectionUrl()
        + testNonStandardConnectionUrl()
        + testPropertiesTransformer()
        + testReplaceLegacyPropertyValues()
        + testTypeEnumCorrectValues()
        + testTypeEnumWrongMysqlxValue()
        - testCSParserTrimHead()
        - testCSParserTrimTail()
    }
  }
  

  namespace com.mysql.cj {
    class com.mysql.cj.ConnectionUrlTest.ConnectionPropertiesTest {
        + transformProperties()
    }
  }
  

  namespace com.mysql.cj {
    class com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator {
        ~ hasNext : boolean
        {static} - ADDRESS_EQUALS_HOST : String[]
        {static} - DB : String[]
        {static} - HOST : String[]
        {static} - KEY_VALUE_HOST : String[]
        {static} - PARAMS : String[]
        {static} - PROTOCOL : String[]
        {static} - STD_HOST : String[]
        {static} - STD_PORT : String[]
        {static} - USER : String[]
        - ceiling : int[]
        - current : int[]
        - next : int[]
        - numberOfHosts : int
        + ConnectionStringGenerator()
        + getDatabase()
        + getHostInfo()
        + getHostParamsCount()
        + getParams()
        + getParamsCount()
        + getProtocol()
        + getUserInfo()
        + hasHostParam()
        + hasNext()
        + hasParam()
        + iterator()
        + next()
        + toString()
        - buildConnectionString()
        - decode()
        - incrementCounter()
    }
  }
  

  namespace com.mysql.cj {
    enum UrlMode {
      INNER_HOSTS_LIST
      OUTER_HOSTS_LIST
      SINGLE_HOST
      hostsCount
    }
  }
  

  namespace com.mysql.cj {
    class com.mysql.cj.MessagesTest {
        + testLocalizedErrorMessages()
    }
  }
  

  namespace com.mysql.cj {
    class com.mysql.cj.ServerVersionTest {
        + testComparison()
        + testEqualsAndHash()
        + testMeetsMinimum()
        + testNotParsable()
        + testNumericVersionToString()
        + testParsedVersion()
    }
  }
  

  com.mysql.cj.ConnectionUrlTest +-down- com.mysql.cj.ConnectionUrlTest.ConnectionPropertiesTest
  com.mysql.cj.ConnectionUrlTest +-down- com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator
  com.mysql.cj.ConnectionUrlTest.ConnectionPropertiesTest .up.|> ConnectionPropertiesTransform
  com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator .up.|> Iterable
  com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator .up.|> Iterator
  com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator o-- com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator.UrlMode : urlMode
  com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator +-down- com.mysql.cj.ConnectionUrlTest.ConnectionStringGenerator.UrlMode


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
