@startuml

title __AUTHENTICATION's Class Diagram__\n

  namespace com.mysql.cj {
    namespace protocol {
      namespace a {
        namespace authentication {
          class com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin {
              {static} + PLUGIN_NAME : String
              + destroy()
              + getProtocolPluginName()
              + init()
              + nextAuthenticationStep()
              + reset()
              # encryptPassword()
          }
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace a {
        namespace authentication {
          enum AuthStage {
            FAST_AUTH_COMPLETE
            FAST_AUTH_READ_RESULT
            FAST_AUTH_SEND_SCRAMBLE
            FULL_AUTH
          }
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace a {
        namespace authentication {
          class com.mysql.cj.protocol.a.authentication.MysqlClearPasswordPlugin {
              - password : String
              - protocol : Protocol<NativePacketPayload>
              + destroy()
              + getProtocolPluginName()
              + init()
              + isReusable()
              + nextAuthenticationStep()
              + requiresConfidentiality()
              + setAuthenticationParameters()
          }
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace a {
        namespace authentication {
          class com.mysql.cj.protocol.a.authentication.MysqlNativePasswordPlugin {
              - password : String
              - protocol : Protocol<NativePacketPayload>
              + destroy()
              + getProtocolPluginName()
              + init()
              + isReusable()
              + nextAuthenticationStep()
              + requiresConfidentiality()
              + setAuthenticationParameters()
          }
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace a {
        namespace authentication {
          class com.mysql.cj.protocol.a.authentication.MysqlOldPasswordPlugin {
              - password : String
              - protocol : Protocol<NativePacketPayload>
              + destroy()
              + getProtocolPluginName()
              + init()
              + isReusable()
              + nextAuthenticationStep()
              + requiresConfidentiality()
              + setAuthenticationParameters()
              {static} - hashPre41Password()
              {static} - newCrypt()
              {static} - newHash()
          }
        }
      }
    }
  }
  

  namespace com.mysql.cj {
    namespace protocol {
      namespace a {
        namespace authentication {
          class com.mysql.cj.protocol.a.authentication.Sha256PasswordPlugin {
              {static} + PLUGIN_NAME : String
              # password : String
              # protocol : Protocol<NativePacketPayload>
              # publicKeyRequested : boolean
              # publicKeyString : String
              # seed : String
              # serverRSAPublicKeyFile : RuntimeProperty<String>
              + destroy()
              + getProtocolPluginName()
              + init()
              + isReusable()
              + nextAuthenticationStep()
              + requiresConfidentiality()
              + setAuthenticationParameters()
              # encryptPassword()
              # encryptPassword()
              {static} # readRSAKey()
          }
        }
      }
    }
  }
  

  com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin o-- com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.AuthStage : stage
  com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin +-down- com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.AuthStage
  com.mysql.cj.protocol.a.authentication.MysqlClearPasswordPlugin .up.|> AuthenticationPlugin
  com.mysql.cj.protocol.a.authentication.MysqlNativePasswordPlugin .up.|> AuthenticationPlugin
  com.mysql.cj.protocol.a.authentication.MysqlOldPasswordPlugin .up.|> AuthenticationPlugin
  com.mysql.cj.protocol.a.authentication.Sha256PasswordPlugin .up.|> AuthenticationPlugin


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
